# Generated by Django 5.0.3 on 2024-04-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_modified',
            new_name='updated_at',
        ),
    ]
