# Generated by Django 5.0.3 on 2024-03-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=100, verbose_name='Nombre Empresa')),
                ('legal_name', models.CharField(max_length=100, verbose_name='Nombre Legal')),
                ('email', models.EmailField(max_length=70, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono Fijo')),
                ('mobile_phone', models.CharField(blank=True, max_length=10, verbose_name='Teléfono Movil')),
                ('web_site', models.CharField(blank=True, max_length=100, verbose_name='Página Web')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
