# Generated by Django 5.0.3 on 2024-03-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Impuesto'),
        ),
    ]
