# Generated by Django 5.0.3 on 2024-03-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_company_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=9, verbose_name='Telefono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('term', models.BooleanField(verbose_name='Terminos y Condiciones')),
            ],
        ),
    ]
